apiVersion: v1
kind: Service
metadata:
  name: reverseproxy-svc
  labels:
    app: reverseproxy
spec:
  selector:
    app: reverseproxy
  ports:
  - protocol: TCP
    name: "8080"
    port: 8080
    targetPort: 8080